import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeModeScript } from "flowbite-react";
import "./globals.css";
import ToastComponent from "./components/Toast/Toast";
import { NotificationStoreProvider } from "@/lib/zustand/providers/NotificationStateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Flowbite React",
  description: "Generated by create flowbite react",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ThemeModeScript />
      </head>
      <body className={inter.className}>
        <NotificationStoreProvider>
          {children}
          <ToastComponent />
        </NotificationStoreProvider>
      </body>
    </html>
  );
}
